### ISSUE TITLE
JustColumns and ServerColumns are broken

### ISSUE THREAD

**Issue by REDFirmware** [puckzxz/NotAnotherAnimeTheme#117]
Hello, it's to say that the columns themes are glitched, I use 3 columns and that what it do to me:
![dfsfdsfdssgfdg](https://user-images.githubusercontent.com/49937350/56639630-672f4700-6671-11e9-9072-f408bae1ee57.PNG)

**Comment by puckzxz** [comment]
Discord received an update that broke many themes and plugins.  We are actively fixing issues and updates will be rolling out over the next few days.

**Comment by Qu4k3** [comment]
Resfreshing or restarting Discord app will actually fix your problem :)

**Comment by REDFirmware** [comment]
I tried many time and nothing work

**Comment by puckzxz** [comment]
If you're still having issues we'd be happy to assist in the support server.

https://discord.gg/FdZhbjY
