### ISSUE TITLE
Update broke the theme...again

### ISSUE THREAD

**Issue by luxidoptera** [puckzxz/NotAnotherAnimeTheme#138]
Yikes my dude. The latest update to Discord seems to have entirely busted many aspects of the theme. So many things have become unskinned that it'd be easier to list the things that are still skinned: the bottom username/"playing" info, the Activity homepage, the users list in DMs/servers, the channel list in servers, and the text field. Everything else is broken and has become unskinned. Tested with the latest uploaded version, which has the same issue.

For the record, I'm on PTB.

![image](https://user-images.githubusercontent.com/15697751/65362192-80163700-dbd4-11e9-8d32-58b2cd0db189.png)

**Comment by puckzxz** [comment]
Fixed in this commit https://github.com/puckzxz/NotAnotherAnimeTheme/commit/1252acb3abfa7b4059ca9e196c9b476209e05041

Thank you for your patience.
