### ISSUE TITLE
Background image not properly appearing

### ISSUE THREAD

**Issue by luxidoptera** [puckzxz/NotAnotherAnimeTheme#141]
Just refreshed my client to update my nickname in a server, and I'm now having an issue where my background image is not showing up, except for a single-pixel sliver at the very top of the window. It looks like it might be an issue with the overlay used to darken the image.

![image](https://user-images.githubusercontent.com/15697751/66542992-18cc1280-eb02-11e9-8d09-32f7416ab058.png)

For the record, this was working ok before I refreshed, I'm fairly sure it's not a problem with my image of choice since it does appear to still be up, and I have not modified the code in my copy of the theme at all recently.

**Comment by puckzxz** [comment]
What Discord version are you running? Stable, PTB or Canary?

**Comment by puckzxz** [comment]
This commit should fix the issue https://github.com/puckzxz/NotAnotherAnimeTheme/commit/028008340373145ae6cfa56ba92cff9ac30251a5.
I'm not seeing the issue on Stable, PTB and Canary now

**Comment by luxidoptera** [comment]
Sorry, forgot to mention my commit, I run PTB. And yea that fixed the issue, ty!
