### ISSUE TITLE
Folder unread messages not showing

### ISSUE THREAD

**Issue by Aimshock** [puckzxz/NotAnotherAnimeTheme#142]
As the newest Discord Folder update was out, you couldn't see unread messages anymore while using the Theme.

**Comment by egold555** [comment]
Happens to me as well. 

BD: 0.3.2
BBD: 0.2.17
NotAnotherAnimeTheme: Latest version
2 columns

**Comment by puckzxz** [comment]
Fixed in this commit https://github.com/puckzxz/NotAnotherAnimeTheme/commit/3d367cbf42160e7be45721e027e310894a55a1fa
