### ISSUE TITLE
Chat color same color as name color

### ISSUE THREAD

**Issue by Rias62** [puckzxz/NotAnotherAnimeTheme#150]
I recently uninstalled this theme and reinstalled, but I can't get some of my settings to be the same. On the old installation I had it where the text color from users in servers was the same color as their role. I can't seem to get it to be the same, any idea?

Thanks.

**Comment by puckzxz** [comment]
That is a BetterDiscord option that is separate from the theme.

You can find it if you go to your BetterDiscord options

![InkedDiscord_sKDiAfJNH3_LI](https://user-images.githubusercontent.com/10362744/70962561-acb2e100-2053-11ea-85e1-5277672be046.jpg)
