### ISSUE TITLE
Theme seems to not be working with css

### ISSUE THREAD

**Issue by SugarCraftUnlimited** [puckzxz/NotAnotherAnimeTheme#151]
When i put the .css into the folder and applied it, no image.
What i did was i put the theme into the css editor, and many issues were pooping up on the first two lines

**Comment by puckzxz** [comment]
Can you upload the file you were trying to use?

I am not able to reproduce this issue.

**Comment by SugarCraftUnlimited** [comment]
I'm stupid, lol. I figured it out, sorry if i wasted your time. I misplaced something and it caused it to not work.

**Comment by SunRaysFalls** [comment]
Neither I. Theme should work out of the box.
