### ISSUE TITLE
Multiple Columns don't work anymore

### ISSUE THREAD

**Issue by Escartem** [puckzxz/NotAnotherAnimeTheme#153]
### Multiple columns don't work anymore, the background works but there is only one column
**Double Column :** 
![image](https://user-images.githubusercontent.com/43405304/78121323-8bf87680-740b-11ea-9d36-f543e4ab43a3.png)
**Quadruple Column :** 
![image](https://user-images.githubusercontent.com/43405304/78121877-3a042080-740c-11ea-9d17-786991197dfa.png)

**Discord version:** 

- 0.0.306

**BandagedBD informations :** 

- Stable 57119 (a7a1673)
- BBD 0.3.2 (14e18c7)
- Host 0.0.306
- Injector 0.3.3
- Windows 10 64-Bit (10.0.18362)

**Comment by puckzxz** [comment]
This has been fixed.  Please restart your Discord client to see the changes

**Comment by Escartem** [comment]
Thank you
