### ISSUE TITLE
Crashing Issue

### ISSUE THREAD

**Issue by TerableCoder** [puckzxz/NotAnotherAnimeTheme#160]
Within the past 2 weeks, when I try to click "Shift + Enter" in chat, Discord crashes.

**Comment by puckzxz** [comment]
This is a BetterDiscord issue and it has already been fixed, you just need to reinstall BetterDiscord

![image](https://user-images.githubusercontent.com/10362744/110225627-61355e80-7eb5-11eb-8b91-7237c0f1811b.png)
