### ISSUE TITLE
Location of Home button, public server button is not aligned with the server icons.

### ISSUE THREAD

**Issue by Spinicle** [puckzxz/NotAnotherAnimeTheme#164]
The location of both the home button and the public server button ( Explore public server button by discord ), is not aligned with the server icons, they are both a bit to the left which is kind of annoying. Not only that, the white line that you get when you hover over the home button, public server button and the add server button is not aligned with the buttons themselves. This too is annoying.

I hope this can be fixed.

**Comment by puckzxz** [comment]
As far as I know all of these should be fixed with V3.  The placement of the home icon does require disabling the BetterDiscord public servers button for it to be properly aligned
