### ISSUE TITLE
Big User Popout header color is disabled

### ISSUE THREAD

**Issue by PatheticMustan** [puckzxz/NotAnotherAnimeTheme#180]
In the big user popout, the header color (it seems to be `background-color` in `.profileBanner-33-uE1`) is overwritten.
The header still displays properly if it's a gif or image, but is disabled if it's just a solid color.

small user popout solid color
![image](https://user-images.githubusercontent.com/35382971/140440113-0ace689e-5bfd-42f5-8cb9-4bbb3b135b9d.png)

big user popout solid color
![image](https://user-images.githubusercontent.com/35382971/140440122-49f05c26-d4f8-498c-b4d3-4c726edb168a.png)

big user popout file
![image](https://user-images.githubusercontent.com/35382971/140440167-4b2f5cab-fda6-492b-bd79-811427eb4641.png)

**Comment by puckzxz** [comment]
The small user popout is intended to be like that.  As for the big user popout I can't reproduce these issues on v3 of the theme.

**Comment by PatheticMustan** [comment]
![image](https://user-images.githubusercontent.com/35382971/140452385-487b9744-5a3f-45a2-8749-a903dc00d22e.png)
![image](https://user-images.githubusercontent.com/35382971/140452388-352c87a2-9458-4f0d-8789-e002a5804b9d.png)

![image](https://user-images.githubusercontent.com/35382971/140452504-3aa4a4cc-8dd5-4aae-ba96-e57a6e194d51.png)

![image](https://user-images.githubusercontent.com/35382971/140452770-aa379e4d-b7b6-42f1-bc89-f9533bca69e9.png)


I'm pretty sure I've updated to the latest...

The line that's overriding it is `https://puckzxz.github.io/NotAnotherAnimeTheme/build/v3/naat.v3.css`, which I'm pretty sure is just the theme file. The rule is `.profileBanner-33-uE1{background-color:initial!important}`

I'm not sure what the line does, but removing it seems to fix the issue...?

**Comment by puckzxz** [comment]
So, if I'm understanding this right you want to see the solid profile color on the big user pop-out?  I kept the image but not a solid color for it since the image is a bit more personable

**Comment by PatheticMustan** [comment]
Ah, I thought it was unintended, since the solid color shows up in the small user pop out, but not the big user pop out. But that was what I was thinking, yeah.

**Comment by puckzxz** [comment]
Fully intended, the solid color on the small popout isn't very distracting although when it's on the big popout it takes up a lot of space with one solid blank color.  The images a person uploads can say a lot about them so I keep them on the big popout, you can also see them better on the big popout too

**Comment by PatheticMustan** [comment]
well then! thanks for being super responsive :D
