### ISSUE TITLE
Asking for change custom font

### ISSUE THREAD

**Issue by YuuJinS** [puckzxz/NotAnotherAnimeTheme#184]
Where can I change font in theme
I really don't want to using BetterDiscord's Custom CSS

**Comment by pp0236** [comment]
![1nKhtcIBTq](https://user-images.githubusercontent.com/54238880/148682962-9d9a1c1c-b5ca-4a93-b002-c85808e42fd5.png)

**Comment by puckzxz** [comment]
Import a font or install one on your system

If you're importing a font from the web you'll need to import it like this near the top of the theme file
```css
@import url(https://fonts.googleapis.com/css?family=Open+Sans);
```
Websites should give you a URL you can just copy and paste, if you're using a font that's installed on your system or you're planning to just install the font on your system then you can ignore this import step

Once you have a font all you need to do is apply it to all elements in the client
```css
* {
  font-family: 'My Font Name';
}
```
Replace the `'My Font Name'` with the name of your font

**Comment by YuuJinS** [comment]
> 

Thanks a lot.
