### ISSUE TITLE
columns

### ISSUE THREAD

**Issue by vamqiez** [puckzxz/NotAnotherAnimeTheme#190]
how do i change my server columns to single? its not working

**Comment by g2Ningyo** [comment]
> how do i change my server columns to single? its not working

Open the theme and change it there, its written down, don't open issues when you cant even read mate.

**Comment by vamqiez** [comment]
> > how do i change my server columns to single? its not working
> 
> Open the theme and change it there, its written down, don't open issues when you cant even read mate.

um lol, ?
![Capture](https://user-images.githubusercontent.com/97687896/149365541-78792bb3-0ea0-4655-ab1f-4493e72914f5.PNG)
what do i even do here? ive tried about everything..

**Comment by g2Ningyo** [comment]
yeah right bellow that its the --server-listing-width: 126px, change it to 72, you are either blind or stupid or you cant read, also i'm here cause i work on the theme with puck and the others, please dont come up with stupid questions and dont insult us or question our work blind man :)

**Comment by vamqiez** [comment]
> 

wasnt trying to insult you at all, i was a bit confused and maybe i didnt get it correctly. thank you very much for your help

**Comment by GHOSTopLive** [comment]
single column - 62 for 1366*768
