### ISSUE TITLE
An Extreme issue

### ISSUE THREAD

**Issue by N0V420** [puckzxz/NotAnotherAnimeTheme#192]
I CANT SEE THE THEMES TAB IN BETTER DISCORD BECAUSE OF THIS THEME 
![image](https://user-images.githubusercontent.com/98670093/151714874-b900e92a-3ef7-4c14-80e5-d2306a1e0c43.png)
thats all i see

**Comment by N0V420** [comment]
please fix this issue i cant change themes

**Comment by puckzxz** [comment]
This theme doesn't even touch any of those options

**Comment by N0V420** [comment]
what does that even mean?

**Comment by puckzxz** [comment]
That means my theme isn't "hiding the themes button" so this is neither my fault nor my problem

**Comment by N0V420** [comment]
how did my themes tab dissapear

**Comment by puckzxz** [comment]
> how did my themes tab dissapear

I don't know ¯\\_(ツ)_/¯, what did you do to your client? From your screenshot could you be on an older version of BetterDiscord?
