### ISSUE TITLE
Home icon bug?

### ISSUE THREAD

**Issue by gamersindo1223** [puckzxz/NotAnotherAnimeTheme#201]
![image](https://user-images.githubusercontent.com/76719536/222691812-021a7501-4faa-4c30-b00b-92e5234f4278.png)
All my servers that didn't have any picture will have the home icon as the icon

**Comment by puckzxz** [comment]
Fixed in this commit, https://github.com/puckzxz/NotAnotherAnimeTheme/commit/6f15125f33798e06fa49f718afcdd54c201afb15
