### ISSUE TITLE
Discords latest update broke some stuff

### ISSUE THREAD

**Issue by iiNekoMattyii** [puckzxz/NotAnotherAnimeTheme#212]
the chat transparency and bottom bar where you change your status.

![image](https://github.com/puckzxz/NotAnotherAnimeTheme/assets/69323445/cd85cba0-6625-4470-b733-933883bfd22b)

**Comment by DailyEndermite** [comment]
same for me, def discord update problem

**Comment by DustyDingleBobby** [comment]
can confirm same for me as well

**Comment by Lukepasky2** [comment]
same for me, the discord update broke something

**Comment by puckzxz** [comment]
👍 fixing currently

**Comment by puckzxz** [comment]
> 👍 fixing currently

Fixed in
https://github.com/puckzxz/NotAnotherAnimeTheme/commit/1549750ef7e01940bf7f0ed750556572cfb93685
https://github.com/puckzxz/NotAnotherAnimeTheme/commit/8821f71c5f8d2ca63a9dd57db49e7d71abfe6170
