### ISSUE TITLE
Theme stopped working

### ISSUE THREAD

**Issue by NeoZar** [puckzxz/NotAnotherAnimeTheme#214]
Today the theme stopped working, the latest version of the theme, version Better Discord 1.9.4

**Comment by ChaselJai** [comment]
same

**Comment by pamposzek** [comment]
same here, using OpenAsar. Was working yesterday.

**Comment by DrSalvador555** [comment]
ditto, was working fine, then suddenly nothing works, using vencord.

**Comment by KurozoraKonoi** [comment]
Same issue - logged into discord today and it was not there anymore, despite the theme supposedly activating

**Comment by Zekken27** [comment]
I think it might be more that bc betterdiscord itself's might have been outdated due to disc new's halloween update rather than just an error with the theme itself

**Comment by ChaselJai** [comment]
**Every discord's updates just kill bunch of plugins** bruh

**Comment by Mefuuu** [comment]
that's due to latest pushed update by discord (build configuration). We just have to wait for theme fix by dev

**Comment by puckzxz** [comment]
This issue has been fixed here https://github.com/puckzxz/NotAnotherAnimeTheme/commit/d7dbc5adb85af77ba2042f6ae32a9d694e7080c8 and in follow up commits
