### ISSUE TITLE
theme transparency not working

### ISSUE THREAD

**Issue by iiNekoMattyii** [puckzxz/NotAnotherAnimeTheme#216]
![image](https://github.com/puckzxz/NotAnotherAnimeTheme/assets/69323445/234d49d9-d3f9-448b-aae1-be8b40cb96c7)

**Comment by puckzxz** [comment]
Seems like discord is changing classes, you'll have to wait until I get the update to fix things

**Comment by iiNekoMattyii** [comment]
alright

**Comment by iiNekoMattyii** [comment]
its all working now i'll just close the issue ty puck
