### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by iGetUploaded** [puckzxz/NotAnotherAnimeTheme#220]
Would it be possible to just get the *Rainbow* server ring code? I would like to add it to my RGB theme? if not all good

**Comment by puckzxz** [comment]
You can find a slimmed down version that just contains the columns, and the rainbow server rings here https://github.com/puckzxz/MoreServers/blob/master/css/v2/ms.v2.css

**Comment by iGetUploaded** [comment]
alrighty thanks 💯

**Comment by iGetUploaded** [comment]
Srry for this but anyway to get it to work with DevilBros *ServerColumns* or nah

**Comment by puckzxz** [comment]
I'm sure there's a way too but I don't know it.

**Comment by iGetUploaded** [comment]
Okay ty anyway
