### ISSUE TITLE
The background behind Discover button is not the same color as the rest of the theme after today's Discord update

### ISSUE THREAD

**Issue by Kubby22** [puckzxz/NotAnotherAnimeTheme#225]
There is probably nothing more to add, everything can be seen in the screenshot and the title says it all.

![obrázek_2024-10-01_155526963](https://github.com/user-attachments/assets/aa096ed9-39c1-4e17-bd9d-829953ba5931)

**Comment by puckzxz** [comment]
I will fix this once I receive the update on my end

**Comment by Enrico9431** [comment]
Was the theme also responsible for hiding it in the first place btw?

**Comment by puckzxz** [comment]
Fix here, https://github.com/puckzxz/NotAnotherAnimeTheme/commit/c08530292686ec2cff6b9937711839ffe32ec5a7

> Was the theme also responsible for hiding it in the first place btw?

The theme was not responsible for hiding this in the first place. This is also an entirely separate element from the list of servers you're in, so it appears that Discord wants it to always be visible now

**Comment by puckzxz** [comment]
You could also use this to hide it entirely

```css
.footer_aa1bff {
    display: none !important;
}
```

**Comment by Enrico9431** [comment]
> You could also use this to hide it entirely
> 
> ```css
> .footer_aa1bff {
>     display: none !important;
> }
> ```

If I were to add this to the theme file and would it get deleted when you update the theme? Or would you recommend adding this to the Custom CSS anyway?

**Comment by puckzxz** [comment]
My changes just adjust the transparency but still keep it visible, that snippet above removes it entirely.

Also, any changes to the theme file itself can override the theme by using `!important`
