### ISSUE TITLE
gdn.abstractconcept.studio is not reachable

### ISSUE THREAD

**Issue by Letsplaybar** [puckzxz/NotAnotherAnimeTheme#30]
this theme does not work, because the gdn.abstractconcept.studio page can not be reached from what is being imported
pls. Fix it

**Comment by ImVexed** [comment]
We're aware of this issue and are currently addressing it.

**Comment by ImVexed** [comment]
We've removed the gdn import for the time being, we've fixed and moved this functionality to the Dev branch for the time being.
