### ISSUE TITLE
Rainbow 'Unread' issue

### ISSUE THREAD

**Issue by EnderWeeb132** [puckzxz/NotAnotherAnimeTheme#45]
I can't seem to change the rainbow thing on the Unread Channels thing. No matter what I do it's still rainbow.

**Comment by Qu4k3** [comment]
@EnderWeeb132 Here you got the code regarding your issue. Take a look.
`.guilds-wrapper .guilds .guild.unread:before {
    background: rgba(67, 181, 129, 0.8); /* change default color */
    animation: hue-rotate 3s linear infinite; /* change to animation: none !important; in order to remove the rainbow efect */
}`

**Comment by EnderWeeb132** [comment]
Thanks dude.

**Comment by EnderWeeb132** [comment]
Tried it. Didn't work. I feel that I should mention i'm using the Dual Collums version

**Comment by EnderWeeb132** [comment]
Thanks. Hoping it works

**Comment by Qu4k3** [comment]
Adding this at the end of your theme's css file or in BD's custom css will remove the rainbow effect.

````css
.guilds-wrapper .guilds .guild.unread:before {
animation: none !important;
}
```
