### ISSUE TITLE
Image transparency option?

### ISSUE THREAD

**Issue by claire-rouge** [puckzxz/NotAnotherAnimeTheme#48]
is there a way to edit it? it's a bit dark for my taste

saw that another theme had a way to change it, and would be cool if we could do it on this theme, since I like your theme the most ^^
```
:root {
	--transparencycolor: 0,0,0;		/* default: 0,0,0 */
	--transparencyalpha: 0.15;		/* default: 0.15 */
	--messagetransparency: 0.5;		/* default: 0.5 (set this to 0 to get rid of the black boxes around messages) */
	--memberlistransparency: 0;		/* default: 0 (additional darkness for member list can be changed in case a bright background makes the list hard to read) */
	--accentcolor: 190,78,180; 		/* default: 190,78,180 discord: 114,137,218 bd-blue: 58,113,193*/
	--background: url(link); /* replace the link in url() with your own direct image link to change the background */
	--backdrop: rgba(0,0,0,0.4);	/* default: rgba(0,0,0,0.4) can also be changed to an image like --background */
}
```
code from - https://github.com/mwittrien/BetterDiscordAddons/tree/master/Themes/BasicBackground

**Comment by claire-rouge** [comment]
oh nice, guess I'll just wait :P

**Comment by puckzxz** [comment]
Alright, I added the ability to customize transparency.  I'm going to leave this issue open just in case, but if these work for you then feel free to close the issue.
https://github.com/puckzxz/NotAnotherAnimeTheme/commit/6e3ded7e22679beef57611cacbe64c1a41360720

**Comment by claire-rouge** [comment]
It works, so I'm closing it.
thank you 👍
