### ISSUE TITLE
Cannot change font color in the newest update.

### ISSUE THREAD

**Issue by FoxySox** [puckzxz/NotAnotherAnimeTheme#53]
/* Edit this to change the color and weight of the text */
.theme-dark .message-group .comment .markup {
color: rgb(0, 255, 255)
}

Does absolutely nothing typing font stays white. Already re-downloaded the newest updates from the theme,  I can change every other color for everything other than the text of what people say in the channels I am in.

**Comment by Qu4k3** [comment]
Hi @FoxySox, Discord have received an update recently and the .theme.css has not been updated yet.
Meanwhile, you can change the color using this code.
`.theme-dark .markup-2BOw-j {
    color: #dcddde;
}`

**Comment by FoxySox** [comment]
Thank you, this has fixed it. silly updates on discord. ree. 👍
