### ISSUE TITLE
transparent

### ISSUE THREAD

**Issue by claire-rouge** [puckzxz/NotAnotherAnimeTheme#57]
![bilde](https://user-images.githubusercontent.com/15875197/43676374-8d691b58-97f0-11e8-9b02-930d01e5fe7c.png)

as you can see it only changes the left side when changing values, discord prob changes some of the css names, since thats what they have been doing the last few weeks. I'll just have it at 0.8 now until its fixed 
(and brighten up the photo in potoshop)

**Comment by Qu4k3** [comment]
Thanks for noticing and tell us about it, we are currently working on a rework of the .theme.css to be easier to customize. It will be released in the next hours.

I'll close this issue then.
