### ISSUE TITLE
Server list lost its background, custom DM icon no longer works

### ISSUE THREAD

**Issue by luxidoptera** [puckzxz/NotAnotherAnimeTheme#99]
Yo, this is just a quick alert that after a recent Discord update (I'm on PTB, for clarity), the server list has lost its background, and the same update also seems to have broken the custom DM icon.

![image](https://user-images.githubusercontent.com/15697751/53985504-c3ea9880-40e9-11e9-8ebb-050bd4911686.png)

**Comment by puckzxz** [comment]
Unfortunately Discord doesn't roll out updates to everyone at once even if they're using PTB or Canary so as soon as I get the update I'll push a fix

**Comment by puckzxz** [comment]
This issue has been fixed.  You will be able to see the changes after restarting your client.
